MODULE interface

  IMPLICIT NONE

  INTEGER, PARAMETER :: NRIB = 1               !       WIDTH OF THE ZIGZAG NANORIBBON
  INTEGER, PARAMETER :: NGRIDX = 8          !       NUMBER OF POINTS IN THE kx AXIS
  INTEGER, PARAMETER :: NGRIDP = 16 !             !       NUMBER OF POINTS IN THE p AXIS
  INTEGER, PARAMETER :: M = 1        ! SIGN OF THE 'BRANCH': 0 = KATUSNORI, +-1 = MARTINS' BRANCHES
  REAL (KIND=8), PARAMETER  :: PI = DACOS(-1.D0)                         !    3.1415...

  REAL (KIND=8), DIMENSION(-NGRIDX:NGRIDX,-NGRIDP:NGRIDP) :: FKNP      !       TRANSCENDENTAL FUNCTION
  REAL (KIND=8), DIMENSION(-NGRIDX:NGRIDX,1:4*NRIB+1) :: ROOTS       !       ROOTS OF TRANSCENDENTAL FUNCTION
  REAL (KIND=8), DIMENSION(-NGRIDX:NGRIDX,1:4*NRIB+1) :: ENERGY1     ! ENERGIES
  REAL (KIND=8), DIMENSION(-NGRIDX:NGRIDX,1:4*NRIB+1) :: ENERGY2

  REAL (KIND=8), DIMENSION(-NGRIDP:NGRIDP) :: P                !       QUASI-MOMENTUM P

  REAL (KIND=8),DIMENSION(1:100) :: NORMA
  REAL (KIND=8), DIMENSION(-NGRIDX:NGRIDX,1:4*NRIB+1) :: PSI_A     !WAVE FUNCTION FOR THE A SITE
  
END MODULE interface
