MODULE TRISECT_LIB

  !OVERLOADING FOR THE TRISECT FUNCTION
  INTERFACE TRISECT
     MODULE PROCEDURE TRISECT, TRISECT_ 
  END INTERFACE TRISECT

CONTAINS
  !TRISECT IS A SUBROUTINE THAT FINDS A ROOT OF A FUNCTION GIVEN THE INTERVAL [A,B]
  !IT PROCEEDS AS TO DIVIDE THE INTERVAL IN 3 PARTS AND CHOOSING OF THE THREE TO
  !RECURSIVELY FUNNEL THE INTERVALS INTO THE ROOTS FOR A GIVEN ACCURACY
  RECURSIVE SUBROUTINE TRISECT(F, A, B)
    REAL(KIND=8) :: F, A, B, IA, IB, SEP
    REAL(KIND=8) :: FA,FB, ERROR, DELTA

    DELTA = 1.D-15

    PRINT *, 'STARTING TRISECT ROUTINE'

    FA = F(A)
    FB = F(B)
    ERROR = B-A

    IF(ERROR .LE. DELTA) THEN
       PRINT *, 'PRECISION REACHED, EXITING ROUTINE.'
       RETURN
    END IF

    PRINT *, 'A = ,',A ,'        B= ', B
    PRINT *, 'F(A) = ,',F(A) ,'        F(B)= ', F(B)

    SEP = ERROR/3.D0
    IA = A + SEP
    IB = B - SEP

    PRINT *, 'SEPARATOR = ,',SEP
    PRINT *, 'IA = ,',IA ,'        IB= ', IB
    PRINT *, 'F(IA) = ,',F(IA) ,'        F(IB)= ', F(IB)

    IF(ABS(SIGN(1.D0,F(IA)) - SIGN(1.D0,F(A))) .GE. 1.D-15) THEN
       CALL TRISECT(F, A, IA)
    ELSE IF(ABS(SIGN(1.D0,F(IB)) - SIGN(1.D0,F(B))) .GE. 1.D-15 ) THEN
       CALL TRISECT(F, IB, B)
    ELSE
       CALL TRISECT(F,IA,IB)
    END IF

    RETURN

  END SUBROUTINE TRISECT

  RECURSIVE SUBROUTINE TRISECT_(F, K, N, M, LOWER, UPPER, R)
    INTEGER :: N, M
    REAL(KIND=8) :: K

    REAL(KIND=8) :: F, LOWER, UPPER, R, A, B, IA, IB, SEP
    REAL(KIND=8) :: FA, FB, ERROR, DELTA

    DELTA = 1.D-15

    A = LOWER
    B = UPPER


    PRINT *, 'STARTING TRISECT ROUTINE WITH PARAMETER:'
    PRINT '(A4,F18.15,1X,A4,I5.3,1X,A4,I5.1)', 'K = ', K, 'N = ', N, 'M = ', M
    PRINT*,

    FA = F(K,A,N,M)
    FB = F(K,B,N,M)
    ERROR = B-A

    PRINT '(A4,F18.15,1X,A4,F18.15)', 'A = ',A ,'B = ', B
    PRINT '(A7,F18.15,1X,A7,F18.15)', 'F(A) = ',F(K,A,N,M) ,'F(B)= ', F(K,B,N,M)

    IF(ERROR .LE. DELTA) THEN
       R = A
       PRINT *, '----------PRECISION REACHED, EXITING ROUTINE.------------'
       RETURN
    END IF

    SEP = ERROR/3.D0
    IA = A + SEP
    IB = B - SEP

    PRINT '(A12,F18.15)', 'SEPARATOR = ',SEP
    PRINT '(A5,F18.15,1X,A5,F18.15)', 'IA = ',IA ,'IB = ', IB
    PRINT '(A8,F18.15,1X,A8,F18.15)', 'F(IA) = ',F(K,IA,N,M) ,'F(IB)= ', F(K,IB,N,M)

    IF(ABS(SIGN(1.D0,F(K,IA,N,M)) - SIGN(1.D0,F(K,A,N,M))) .GE. 1.D-15) THEN
       PRINT *,
       CALL TRISECT(F, K, N, M, A, IA, R)
    ELSE IF(ABS(SIGN(1.D0,F(K,IB,N,M)) - SIGN(1.D0,F(K,B,N,M))) .GE. 1.D-15 ) THEN
       PRINT *,
       CALL TRISECT(F, K, N, M, IB, B, R)
    ELSE
       PRINT *,
       CALL TRISECT(F, K, N, M, IA, IB, R)
    END IF

    RETURN

  END SUBROUTINE TRISECT_
END MODULE TRISECT_LIB

