MODULE PLOT
  IMPLICIT NONE

  INTERFACE WRITE_RESULT
     MODULE PROCEDURE WRITE_VECTOR, WRITE_VECTOR_MATRIX
  END INTERFACE WRITE_RESULT
  
  CONTAINS    
    SUBROUTINE WRITE_VECTOR(FILE_UNIT,X,Y)

      INTEGER,  INTENT(IN)           ::  FILE_UNIT
      REAL(KIND=8), INTENT(IN)           ::  X(:)
      REAL(KIND=8), INTENT(IN) ::  Y(:)

      INTEGER:: I,NDATA

      NDATA = SIZE(X)

      PRINT *, 'WRITING TO FILE, UNIT:', FILE_UNIT
      
      DO I = 1, NDATA
         WRITE ( FILE_UNIT, * ) X(I), Y(I)
      END DO

      PRINT *, 'SUCCESSFULLY WROTE FILE, UNIT:',FILE_UNIT

    END SUBROUTINE WRITE_VECTOR

    SUBROUTINE WRITE_VECTOR_MATRIX(FILE_UNIT,X,Y)
      INTEGER, INTENT(IN) :: FILE_UNIT
      REAL(KIND=8), INTENT(IN) :: X(:)
      REAL(KIND=8), INTENT(IN) :: Y(:,:)

      INTEGER :: NX,NY,N_CURVES,I1,I2

      NX = SIZE(X)
      NY = SIZE(Y,DIM=1)

      PRINT *, 'WRITING TO FILE, UNIT:', FILE_UNIT
      IF(NX .NE. NY) THEN
         PRINT *, 'SIZES ARE NOT COMPATIBLE.'
         RETURN
      END IF

      N_CURVES = SIZE(Y,DIM=2)

      DO I1 = 1,NX
         WRITE(FILE_UNIT, *) X(I1), (Y(I1,I2),I2=1,N_CURVES)
      END DO
      PRINT *, 'SUCESSFULLY WROTE TO FILE, UNIT:', FILE_UNIT

    END SUBROUTINE WRITE_VECTOR_MATRIX

END MODULE PLOT
