MODULE PLOT
  IMPLICIT NONE

  INTERFACE WRITE_RESULT
     MODULE PROCEDURE WRITE_VECTOR, WRITE_VECTOR_MATRIX, WRITE_MATRIX
  END INTERFACE WRITE_RESULT
  
  CONTAINS    
    SUBROUTINE WRITE_VECTOR(X,Y, FILE_NAME)

      CHARACTER(LEN=*),  INTENT(IN)           ::  FILE_NAME
      REAL(KIND=8), INTENT(IN)           ::  X(:)
      REAL(KIND=8), INTENT(IN) ::  Y(:)

      INTEGER:: I,NDATA

      NDATA = SIZE(X)

      PRINT *, 'NAME:', FILE_NAME
      
      DO I = 1, NDATA
         WRITE ( *, * ) X(I), Y(I)
      END DO

      PRINT *, 'SUCCESSFULLY WROTE FILE'

    END SUBROUTINE WRITE_VECTOR

    SUBROUTINE WRITE_VECTOR_MATRIX(X,Y, FILE_NAME)
      CHARACTER(LEN=*), INTENT(IN) :: FILE_NAME
      REAL(KIND=8), INTENT(IN) :: X(:)
      REAL(KIND=8), INTENT(IN) :: Y(:,:)

      INTEGER :: NX,NY,N_CURVES,I1,I2

      NX = SIZE(X)
      NY = SIZE(Y,DIM=1)
      
      IF(NX .NE. NY) THEN
         PRINT *, 'SIZES ARE NOT COMPATIBLE.'
         RETURN
      END IF

      PRINT *, 'NAME:', FILE_NAME

      N_CURVES = SIZE(Y,DIM=2)

      DO I1 = 1,NX
         WRITE(*, *) X(I1), (Y(I1,I2),I2=1,N_CURVES)
      END DO
      PRINT *, 'SUCCESSFULLY WROTE TO FILE'

    END SUBROUTINE WRITE_VECTOR_MATRIX

    SUBROUTINE WRITE_MATRIX(Y, FILE_NAME)
      CHARACTER(LEN=*), INTENT(IN) :: FILE_NAME

      REAL(KIND=8), INTENT(IN) :: Y(:,:)

      INTEGER :: NX, N_CURVES,I1,I2

      NX = SIZE(Y,DIM=1)

      PRINT *, 'NAME:', FILE_NAME

      N_CURVES = SIZE(Y,DIM=2)

      DO I1 = 1,NX
         WRITE(*,*) (Y(I1,I2), I2=1,N_CURVES)
      END DO
      PRINT *, 'SUCCESSFULLY WROTE TO FILE'

    END SUBROUTINE WRITE_MATRIX

END MODULE PLOT
