PROGRAM ZIGZAGHAND
  USE OGPF
  USE INTERFACE
  USE MY_LIB, ONLY: TRISECT, FTRANS, ENERGY, WRITE_VECTOR, WRITE_VECTOR_MATRIX
  
  IMPLICIT NONE

  REAL (KIND=8), DIMENSION(-NGRIDX:NGRIDX) :: AKX       !WAVE VECTOR IN THE X DIRECTION
  REAL (KIND=8), DIMENSION(-NGRIDP:NGRIDP) :: AKP       !WAVE VECTOR IN THE Y DIRECTION
  REAL (KIND=8), DIMENSION(-NGRIDX:NGRIDX) :: A0X       !AUXILIARY
  REAL (KIND=8), DIMENSION(-NGRIDP:NGRIDP) :: A0P       !AUXILIARY

  REAL (KIND=8), DIMENSION(1:9,1:8) :: REFERENCE
  REAL (KIND=8), DIMENSION(1:9) :: REF
  
  INTEGER, DIMENSION(-NGRIDX:NGRIDX) :: AUX_N                       

  INTEGER :: I1,I2,I3,I,T2          !DO LOOP COUNTERS
  REAL (KIND=8) :: A1,A2,A3,T1,T3,R     !AUXILIARY
  LOGICAL :: SIGNAL                   !AUX FOR ROOT FINDING

  TYPE(GPF) :: MATPLOT                !GNUPLOT EXTENSION
  
  !THIS PROGRAM CALCULATES THE 'CORRECTED' TRANSCENDENTAL FUNCTION F(k,N,p) DEFINED
  !IN KATSUNORI'S PAPER [Sci. Technol. Adv. Mater. 11 (2010) 054504]

  !GENERATING THE VECTORS FOR kx and for p
  A0X  = (/ (DBLE(I), I = -NGRIDX, NGRIDX)  /)
  A0P  = (/ (DBLE(I), I = -NGRIDP, NGRIDP)  /)

  AKX(-NGRIDX:NGRIDX) = A0X(-NGRIDX:NGRIDX) * PI/DBLE(NGRIDX)
  AKP(-NGRIDP:NGRIDP) = A0P(-NGRIDP:NGRIDP) * PI/DBLE(NGRIDP)


  PRINT *, 'STARTING PROGRAM WITH PARAMETERS:'
  PRINT '(A4,I5)', 'N = ', NRIB
  PRINT '(A4,I5)', 'K = ', NGRIDX
  PRINT '(A4,I5)', 'P = ', NGRIDP

  !DEFINING THE 'CORRECTED' TRANSCENDENTAL FUNCTION
  DO I1 = -NGRIDX, NGRIDX         !       GOES OVER THE WHOLE k_x AXIS
     DO I2 = -NGRIDP, NGRIDP        !       GOES OVER THE QUASI-MOMENTUM p
        FKNP(I1,I2) = FTRANS(AKX(I1),AKP(I2),NRIB,M)
     END DO
  END DO

  !GETTING THE ROOTS BY BISECTION
  AUX_N = 0 !COUNTER FOR THE NUMBER OF ROOTS
  DO I2 = -NGRIDX,NGRIDX     
     T1 = 0.D0
     T2 = 1
     T3 = 0.D0
     IF(FKNP(I2,0).LT.0.D0) THEN
        SIGNAL = .TRUE.!.FALSE.
     ELSE
        SIGNAL = .FALSE.!.TRUE.
     END IF
     DO I1 = -NGRIDP, NGRIDP
        IF(SIGNAL .AND. FKNP(I2,I1).LT.T1) THEN
           CALL TRISECT(FTRANS, AKX(I2), NRIB, M, AKP(I1-1), AKP(I1),R)
           ROOTS(I2,T2) = R
           T2 = T2+1
           SIGNAL = .NOT.SIGNAL! .FALSE.               !FLIP TO THE NEGATIVE SIGN
        ELSE IF(.NOT.SIGNAL .AND. FKNP(I2,I1).GT.T1) THEN
           CALL TRISECT(FTRANS, AKX(I2), NRIB, M, AKP(I1-1), AKP(I1), R)
           ROOTS(I2,T2) = R
           T2 = T2+1
           SIGNAL = .NOT.SIGNAL!.TRUE.                 !FLIP TO THE POSITIVE SIGN
        END IF
     END DO
     AUX_N(I2) = T2 - 1
  END DO

  !CALCULATING THE ENERGY AS IN MARTINS NOTES
  DO I1 = -NGRIDX, NGRIDX
     DO I2 = 1, AUX_N(I1)
        ENERGY1(I1,I2) = ENERGY(AKX(I1), ROOTS(I1,I2), M)
        ENERGY2(I1,I2) =  -ENERGY(AKX(I1), ROOTS(I1,I2),M)
     END DO
  END DO

  OPEN(UNIT=1,FILE='bandsN=1.dat',STATUS='OLD', ACTION='READ')
  DO I1=1,9
     READ(1,*) REF(I1), (REFERENCE(I1,I2),I2=1,8)
  END DO
  
  CLOSE(1)          


  CALL MATPLOT%OPTIONS('set xrange[0:3.15]; set yrange[0:3]')
  CALL MATPLOT%MULTIPLOT(1,2)
  CALL MATPLOT%PLOT(AKX(0:NGRIDX),ENERGY1(0:NGRIDX,:),'w l')
  CALL MATPLOT%PLOT(REF,REFERENCE,'w l')

  OPEN(UNIT=1,FILE='./results/new/zzhand.dat',STATUS='UNKNOWN')
  OPEN(UNIT=2,FILE='./results/new/energy1dat',STATUS='UNKNOWN')
  OPEN(UNIT=3,FILE='./results/new/energy2.dat',STATUS='UNKNOWN')
  OPEN(UNIT=4,FILE='./results/new/ROOTS.dat',STATUS='UNKNOWN')

  CALL WRITE_VECTOR_MATRIX(1, AKX, FKNP)
  CALL WRITE_VECTOR_MATRIX(2, AKX, ENERGY1)
  CALL WRITE_VECTOR_MATRIX(3, AKX, ENERGY2)
  CALL WRITE_VECTOR_MATRIX(4, AKX, ROOTS)
  
  CLOSE(1)
  CLOSE(2)
  CLOSE(3)
  CLOSE(4)
  
!  CALL MATPLOT%PLOT(AKX,ENERGY2,'w l')

!!$
!!$  DO I2 = -NGRIDX, NGRIDX
!!$     WRITE(*,'(65(F18.5,1X))') AKX(I2), (ROOTS(I2,I1),I1=1,AUX_N(I2))
!!$  END DO
!!$

!!$
!!$  IF(NGRIDX .LT.12) THEN
!!$     CALL MATPLOT%PLOT(AKX,FKNP)
!!$  END IF

!!$ IN CASE I NEED TO PHYSICALLY WRITE IT  
!!$  OPEN(UNIT=1,FILE='./results/new/zzhand.dat',STATUS='UNKNOWN')
!!$  OPEN(UNIT=2,FILE='./results/new/energy1_0.dat',STATUS='UNKNOWN')
!!$  OPEN(UNIT=3,FILE='./results/new/energy2_0.dat',STATUS='UNKNOWN')
!!$  OPEN(UNIT=4,FILE='./results/new/ROOTS.dat',STATUS='UNKNOWN')
!!$
!!$  DO I1 = -NGRIDP, NGRIDP
!!$     WRITE(1,100)AKP(I1),(FKNP(I2,I1),I2=-NGRIDX,NGRIDX)
!!$  END DO  
!!$
!!$  DO I1 = -NGRIDX,-NGRIDX
!!$     WRITE(2,100) AKX(I1),(ENERGY1(I1,I2),I2=1,AUX_N(I1))
!!$     WRITE(3,100) AKX(I1),(ENERGY2(I1,I2),I2=1,AUX_N(I1))
!!$  END DO
!!$
!!$  DO I2 = -NGRIDX,NGRIDX
!!$     WRITE(4,100) 0.D0, (ROOTS(I2,I1), I1=1,AUX_N(I2))
!!$  END DO
!!$
!!$  CLOSE(1)
!!$  CLOSE(3)
!!$  CLOSE(4)
!!$  CLOSE(4)
  
100 FORMAT(65(F8.5,1X))

END PROGRAM ZIGZAGHAND
